### ISSUE TITLE
Bug/Issue Report

### ISSUE THREAD

**Issue by RChutchev** [axtonprice-dev/quickblaze-encrypt#77]
**Describe the bug**
Failed to load CSS and JS from external site.

**To Reproduce**
1. Go to main (home) page.
2. Right click and choose Inspect, go to Network tab
3. See errors

**Expected behavior**
Resources loaded successfully.

**Screenshots**
![Screenshot 2023-07-17 at 3 45 14 AM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/0b07c9c0-8820-4849-b19d-d711d542f291)
![Screenshot 2023-07-17 at 3 45 10 AM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/d929c5ed-3a5a-4ccd-bc35-a76c7ddc79d0)
![Screenshot 2023-07-17 at 3 45 03 AM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/60cd65b3-1c93-4e93-b91b-e5f926a00bf7)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari
 - Chrome version - Version 114.0.5735.133 (Official Build) (x86_64)
 - Safari version - Version 16.5 (18615.2.9.11.4)

**Comment by axtonprice** [comment]
@RChutchev Please confirm the QuickBlaze version and release channel relevant to this issue. Thanks

**Comment by RChutchev** [comment]
Yep, it's relevant to this issue, b/c I've same issue at https://quickblaze.arizon.dev/ right now with resource "https//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css". 

Looks like a country connectivity issue, the country's local DNS (ISP's DNS) isn't returning a response for this domain at all.
![Screenshot 2023-07-17 at 12 56 15 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/a9a3a2d5-54db-45e8-9d02-9b64ba1890c2)
![Screenshot 2023-07-17 at 12 58 19 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/159414f8-73f0-48b8-969f-386b162ddd2c)

**Comment by RChutchev** [comment]
I can change the code to load all resources from the installation domain and put all resources into folders. Otherwise i'll use another CDN (https://cdnjs.com/libraries/bootstrap/5.1.3). Anyway, it's the same for me b/c i use a CloudFlare. I need time to investigate.

**Comment by axtonprice** [comment]
I'm asking for the release channel and release version of QuickBlaze you are using which is relevant to the issue you have described. For example v1.0.0 on channel "main".

**Comment by RChutchev** [comment]
{ "BRANCH": "main", "VERSION":"1.1.15" }

**Comment by axtonprice** [comment]
Thanks, i'll look into it.

**Comment by RChutchev** [comment]
This problem definitely related to the my current country. 
Resources now can't be loaded from Egypt (some time ago everything worked fine). 
This is a possible government regulation related problem. 
DNS flush didn't solve the problem at all. 
Any device has the same problem with quickblaze here.

Physical machine in another country accessed via RDP shows no resources loading errors.

I can only suggest to change the CDN (e.g. Cloudflare) for this resources in the repo or i'll change it locally on my server. Because Cloudflare seems to be more stable.

Also, I see that a new version has been published. 
I'll test that new one and maybe suggest some changes, or i'll do it on my server and create a new pull request. 

Thanks you so much anyway!

**Comment by RChutchev** [comment]
After changing the CDN to Cloudflare, everything works well.
![Screenshot 2023-07-17 at 11 03 30 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/5c6392da-99a1-4110-9e6f-f9086782e0e1)

Should I create a pull request or will you continue to use your chosen CDN?

**Comment by axtonprice** [comment]
The next commit on the canary branch will include a patch for this issue

**Comment by RChutchev** [comment]
Thank you so much!

**Comment by axtonprice** [comment]
Issue patched in latest `canary` commit. Thanks for submitting!
https://github.com/arizon-dev/quickblaze-encrypt/tree/canary

**Comment by RChutchev** [comment]
Hello, 
now I updated server side from CANARY repo.
This issue is here and im getting same errors with files:
URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css
URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js
![Screenshot 2023-08-12 at 10 40 58 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/c808fcad-b0f4-44e2-9a49-b03199cece64)

**Comment by RChutchev** [comment]
This issue on "Database error" page, { "BRANCH": "canary", "VERSION":"1.8.58" }
 
![Screenshot 2023-08-12 at 10 58 40 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/cbf042f9-344c-4bd2-bbfe-862700aa0539)
![Screenshot 2023-08-12 at 10 58 59 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/5a213342-a624-421b-87ec-d6f17456b4a6)
![Screenshot 2023-08-12 at 10 59 12 PM](https://github.com/arizon-dev/quickblaze-encrypt/assets/11131666/63482c7a-6b72-4acd-a318-8720eca03aab)

**Comment by axtonprice** [comment]
Have you correctly formatted your database configuration file?

**Comment by axtonprice** [comment]
> Hello, now I updated server side from CANARY repo. This issue is here and im getting same errors with files: URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js ![Screenshot 2023-08-12 at 10 40 58 PM](https://user-images.githubusercontent.com/11131666/260256117-c808fcad-b0f4-44e2-9a49-b03199cece64.png)

I'm afraid this is not something I can fix as this appears to be an issue on your end. Maybe your network is preventing the connection to the CDN the assets are hosted on?

**Comment by RChutchev** [comment]
> > Hello, now I updated server side from CANARY repo. This issue is here and im getting same errors with files: URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css URL: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js ![Screenshot 2023-08-12 at 10 40 58 PM](https://user-images.githubusercontent.com/11131666/260256117-c808fcad-b0f4-44e2-9a49-b03199cece64.png)
> 
> I'm afraid this is not something I can fix as this appears to be an issue on your end. Maybe your network is preventing the connection to the CDN the assets are hosted on?

Hello, yep, I already said that this problem is country related [here](https://github.com/arizon-dev/quickblaze-encrypt/issues/77#issuecomment-1638690297) and [here](https://github.com/arizon-dev/quickblaze-encrypt/issues/77#issuecomment-1638793030) I wrote that after change a CDN to Cloudflare everything work fine.
I can only suggest to change the CDN (e.g. Cloudflare) for this resources in the repo or i'll change it locally on my server.

**Comment by RChutchev** [comment]
> Have you correctly formatted your database configuration file?

No, but this is not a problem.
The problem is in the resources that will not load, the database was configured later.

**Comment by axtonprice** [comment]
Please ensure the following criteria are met to run the application:

1. Your `Database.env` file exists and is read/writable on the server.
2. Your `Database.env` file is not empty and all fields are filled with correct credentials.
3. The credentials provided have the required permissions to alter the database.

For more information on how the application checks these credentials, please take a look at line 125 of the file `/modules/functions.php`. Or [click here](https://github.com/arizon-dev/quickblaze-encrypt/blob/2b38b980a9b57dd956199e47d1bb2ecb8ff51cca/modules/functions.php#L125).

*(I will admit, this code is messy and there is certainly a much cleaner way to approach this function.)*

**Comment by axtonprice** [comment]
In terms of the CDN, I will potentially look at moving the application resources to an alternative provider on the next major canary release.
